POST http://{{ASSET_MANTLE_CLIENT_HOST}}:{{ASSET_MANTLE_CLIENT_PORT}}/xprt/assets/mint
Content-Type: application/json

{
 "type": "/xprt/assets/mint/request",
 "value": {
    "baseReq": {
      "from": "{{ACCOUNT_1_ADDRESS}}",
      "chain_id": "{{CHAIN_ID}}"
    },
    "fromID":"{{ACCOUNT_1_ID}}",
    "toID":"{{ACCOUNT_1_ID}}",
    "maintainersID":"",
    "classificationID":"",
    "properties": "{{ACCOUNT_1_NAME}}assets{{NONCE}}:{{ACCOUNT_1_NAME}}assets{{NONCE}}, test1:test1",
    "lock": "-1",
    "burn": "-1"
  }
}

> {%
   client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
   client.global.set("assetsMintTxHash", JSON.parse(JSON.stringify(response.body)).txhash)
%}

###
GET http://{{ASSET_MANTLE_CLIENT_HOST}}:{{ASSET_MANTLE_CLIENT_PORT}}/txs/{{assetsMintTxHash}}
Accept: application/json

> {%
   client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
client.test("Response Code Check", function() {
     client.assert(!JSON.parse(JSON.stringify(response.body)).hasOwnProperty("code") , "Response Code is not 0");
 });
%}

###
GET http://{{ASSET_MANTLE_CLIENT_HOST}}:{{ASSET_MANTLE_CLIENT_PORT}}/assets/assets/-
Accept: application/json

> {%
   client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });



        assets = JSON.parse(JSON.stringify(response.body)).result.value.assets.value.list;

        function checkProperty(propertyID, identity){
            properties = identity.value.immutables.value.properties.value.propertyList
             for(i = 0; i < properties.length; i++) {
                 if (propertyID === properties[i].value.id.value.idString){
                     return true;
                 }
             }
             return false;
        }
        function getID(ID){
             assetID = [];
             for (id in ID.value) {
                 if (ID.value.hasOwnProperty(id)){
                     assetID[assetID.length] = ID.value[id].value.idString;
                 }
             }
             return assetID.join(".");
        }
        for (i = 0; i < assets.length; i++) {
            if (checkProperty(client.global.get("ACCOUNT_1_NAME")+"assets"+client.global.get("NONCE"), assets[i])) {
                client.global.set("ACCOUNT_1_ASSET_ID", getID(assets[i].value.id));
            }
        }



%}
###