POST http://{{ASSET_MANTLE_CLIENT_HOST}}:{{ASSET_MANTLE_CLIENT_PORT}}/bank/accounts/{{ACCOUNT_1_ADDRESS}}/transfers
Content-Type: application/json

{
  "base_req": {
    "from": "{{TEST_ACCOUNT_ADDRESS}}",
    "chain_id": "{{CHAIN_ID}}"
  },
  	"amount":[{"denom":"stake","amount":"100"}],
    "mode" : "block"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
  %}

###