GET http://{{ASSET_MANTLE_NODE_HOST}}:{{ASSET_MANTLE_NODE_PORT}}/block?height=1
Accept: application/json

> {%
   client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

   nonce = Math.floor(Math.random() * 100)
   client.global.set("NONCE", nonce)
   client.global.set("ACCOUNT_1_NAME", "account1"+nonce)
   client.global.set("ACCOUNT_2_NAME", "account2"+nonce)
   client.global.set("ACCOUNT_3_NAME", "account3"+nonce)
   client.global.set("ACCOUNT_4_NAME", "account4"+nonce)

%}

###
