
POST http://{{host}}:{{port}}/assets/mint
Content-Type: application/json

{
  "key": {{input}}
}
> {%

 client.test("Request executed successfully",function() {
         client.assert(response.status ===200, "Response id not 200");
 });

 client.test("Headers option exists", function() {
        client.assert(response.body.hasOwnProperty("headers"), "Cannot find 'headers' option in response");
    });

 client.test("Response content-type is json", function() {
        var type = response.contentType.mimeType;
        client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
    });

 client.test("Response content-check", function() {
        var type = response.contentType.json;
        client.assert(type !== " ", "Expected 'some value' but received '" + type + "'");
    });
 %}
###


