GET http://{{ASSET_MANTLE_CLIENT_HOST}}:{{ASSET_MANTLE_CLIENT_PORT}}/splits/splits/test.cGn3HMW8M3t5gMDv-wXa9sseHnA=|eYA_gY99Ft1MaMGPmPIyipHQdyo=*stake
Accept: application/json

> {%
   client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###