PROCESS=persistencecore

apply:
	kubectl apply -k $(PROCESS)

delete:
	kubectl delete -k $(PROCESS)

# debug:
    # port-forward
    # init -genesis
    # get seeds - by calling exposer
    # get genesis and paste in .$BINARY folder
    #
