// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pstake/liquidstake/v1beta1/liquidstake.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ValidatorStatus enumerates the status of a liquid validator.
type ValidatorStatus int32

const (
	// VALIDATOR_STATUS_UNSPECIFIED defines the unspecified invalid status.
	ValidatorStatusUnspecified ValidatorStatus = 0
	// VALIDATOR_STATUS_ACTIVE defines the active, valid status
	ValidatorStatusActive ValidatorStatus = 1
	// VALIDATOR_STATUS_INACTIVE defines the inactive, invalid status
	ValidatorStatusInactive ValidatorStatus = 2
)

var ValidatorStatus_name = map[int32]string{
	0: "VALIDATOR_STATUS_UNSPECIFIED",
	1: "VALIDATOR_STATUS_ACTIVE",
	2: "VALIDATOR_STATUS_INACTIVE",
}

var ValidatorStatus_value = map[string]int32{
	"VALIDATOR_STATUS_UNSPECIFIED": 0,
	"VALIDATOR_STATUS_ACTIVE":      1,
	"VALIDATOR_STATUS_INACTIVE":    2,
}

func (x ValidatorStatus) String() string {
	return proto.EnumName(ValidatorStatus_name, int32(x))
}

func (ValidatorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8f87e6d47a5a3bba, []int{0}
}

// Params defines the set of params for the liquidstake module.
type Params struct {
	// LiquidBondDenom specifies the denomination of the token receiving after
	// liquid stake, The value is calculated through NetAmount.
	LiquidBondDenom string `protobuf:"bytes,1,opt,name=liquid_bond_denom,json=liquidBondDenom,proto3" json:"liquid_bond_denom,omitempty"`
	// WhitelistedValidators specifies the validators elected to become Active
	// Liquid Validators.
	WhitelistedValidators []WhitelistedValidator `protobuf:"bytes,2,rep,name=whitelisted_validators,json=whitelistedValidators,proto3" json:"whitelisted_validators"`
	// UnstakeFeeRate specifies the fee rate when liquid unstake is requested,
	// unbonded by subtracting it from unbondingAmount
	UnstakeFeeRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=unstake_fee_rate,json=unstakeFeeRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"unstake_fee_rate"`
	// LsmDisabled allows to block any msgs that convert staked tokens into
	// stkXPRT through LSM.
	LsmDisabled bool `protobuf:"varint,4,opt,name=lsm_disabled,json=lsmDisabled,proto3" json:"lsm_disabled,omitempty"`
	// MinLiquidStakingAmount specifies the minimum number of coins to be staked
	// to the active liquid validators on liquid staking to minimize decimal loss
	// and consider gas efficiency.
	MinLiquidStakeAmount cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=min_liquid_stake_amount,json=minLiquidStakeAmount,proto3,customtype=cosmossdk.io/math.Int" json:"min_liquid_stake_amount"`
	// CwLockedPoolAddress defines the bech32-encoded address of
	// a CW smart-contract representing a time locked LP (e.g. Superfluid LP).
	CwLockedPoolAddress string `protobuf:"bytes,6,opt,name=cw_locked_pool_address,json=cwLockedPoolAddress,proto3" json:"cw_locked_pool_address,omitempty"`
	// FeeAccountAddress defines the bech32-encoded address of
	// a an account responsible for accumulating protocol fees.
	FeeAccountAddress string `protobuf:"bytes,7,opt,name=fee_account_address,json=feeAccountAddress,proto3" json:"fee_account_address,omitempty"`
	// AutocompoundFeeRate specifies the fee rate for auto redelegating the stake
	// rewards. The fee is taken in favour of the fee account (see
	// FeeAccountAddress).
	AutocompoundFeeRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=autocompound_fee_rate,json=autocompoundFeeRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"autocompound_fee_rate"`
	// WhitelistAdminAddress the bech32-encoded address of an admin authority
	// that is allowed to update whitelisted validators or pause liquidstaking
	// module entirely. The key is controlled by an offchain process that is
	// selecting validators based on a criteria. Pausing of the module can be
	// required during important migrations or failures.
	WhitelistAdminAddress string `protobuf:"bytes,9,opt,name=whitelist_admin_address,json=whitelistAdminAddress,proto3" json:"whitelist_admin_address,omitempty"`
	// ModulePaused is a safety toggle that allows to stop main module functions
	// such as stake/unstake/stake-to-lp and the BeginBlocker logic.
	ModulePaused bool `protobuf:"varint,10,opt,name=module_paused,json=modulePaused,proto3" json:"module_paused,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f87e6d47a5a3bba, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

// WhitelistedValidator consists of the validator operator address and the
// target weight, which is a value for calculating the real weight to be derived
// according to the active status.
type WhitelistedValidator struct {
	// validator_address defines the bech32-encoded address that whitelisted
	// validator
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// target_weight specifies the target weight for liquid staking, unstaking
	// amount, which is a value for calculating the real weight to be derived
	// according to the active status
	TargetWeight cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=target_weight,json=targetWeight,proto3,customtype=cosmossdk.io/math.Int" json:"target_weight"`
}

func (m *WhitelistedValidator) Reset()         { *m = WhitelistedValidator{} }
func (m *WhitelistedValidator) String() string { return proto.CompactTextString(m) }
func (*WhitelistedValidator) ProtoMessage()    {}
func (*WhitelistedValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f87e6d47a5a3bba, []int{1}
}
func (m *WhitelistedValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WhitelistedValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WhitelistedValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WhitelistedValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhitelistedValidator.Merge(m, src)
}
func (m *WhitelistedValidator) XXX_Size() int {
	return m.Size()
}
func (m *WhitelistedValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_WhitelistedValidator.DiscardUnknown(m)
}

var xxx_messageInfo_WhitelistedValidator proto.InternalMessageInfo

// LiquidValidator defines a Validator that can be the target of LiquidStaking
// and LiquidUnstaking, Active, Weight, etc. fields are derived as functions to
// deal with by maintaining consistency with the state of the staking module.
type LiquidValidator struct {
	// operator_address defines the address of the validator's operator; bech
	// encoded in JSON.
	OperatorAddress string `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
}

func (m *LiquidValidator) Reset()         { *m = LiquidValidator{} }
func (m *LiquidValidator) String() string { return proto.CompactTextString(m) }
func (*LiquidValidator) ProtoMessage()    {}
func (*LiquidValidator) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f87e6d47a5a3bba, []int{2}
}
func (m *LiquidValidator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidValidator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidValidator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidValidator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidValidator.Merge(m, src)
}
func (m *LiquidValidator) XXX_Size() int {
	return m.Size()
}
func (m *LiquidValidator) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidValidator.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidValidator proto.InternalMessageInfo

// LiquidValidatorState is type LiquidValidator with state added to return to
// query results.
type LiquidValidatorState struct {
	// operator_address defines the address of the validator's operator; bech
	// encoded in JSON.
	OperatorAddress string `protobuf:"bytes,1,opt,name=operator_address,json=operatorAddress,proto3" json:"operator_address,omitempty"`
	// weight specifies the weight for liquid staking, unstaking amount
	Weight cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=weight,proto3,customtype=cosmossdk.io/math.Int" json:"weight"`
	// status is the liquid validator status
	Status ValidatorStatus `protobuf:"varint,3,opt,name=status,proto3,enum=pstake.liquidstake.v1beta1.ValidatorStatus" json:"status,omitempty"`
	// del_shares define the delegation shares of the validator
	DelShares cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=del_shares,json=delShares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"del_shares"`
	// liquid_tokens define the token amount worth of delegation shares of the
	// validator (slashing applied amount)
	LiquidTokens cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=liquid_tokens,json=liquidTokens,proto3,customtype=cosmossdk.io/math.Int" json:"liquid_tokens"`
}

func (m *LiquidValidatorState) Reset()         { *m = LiquidValidatorState{} }
func (m *LiquidValidatorState) String() string { return proto.CompactTextString(m) }
func (*LiquidValidatorState) ProtoMessage()    {}
func (*LiquidValidatorState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f87e6d47a5a3bba, []int{3}
}
func (m *LiquidValidatorState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidValidatorState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidValidatorState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidValidatorState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidValidatorState.Merge(m, src)
}
func (m *LiquidValidatorState) XXX_Size() int {
	return m.Size()
}
func (m *LiquidValidatorState) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidValidatorState.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidValidatorState proto.InternalMessageInfo

// NetAmountState is type for net amount raw data and mint rate, This is a value
// that depends on the several module state every time, so it is used only for
// calculation and query and is not stored in kv.
type NetAmountState struct {
	// mint_rate is stkXPRTTotalSupply / NetAmount
	MintRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=mint_rate,json=mintRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"mint_rate"`
	// btoken_total_supply returns the total supply of stk/uxprt (stkXPRT denom)
	StkxprtTotalSupply cosmossdk_io_math.Int `protobuf:"bytes,2,opt,name=stkxprt_total_supply,json=stkxprtTotalSupply,proto3,customtype=cosmossdk.io/math.Int" json:"stkxprt_total_supply"`
	// net_amount is proxy account's native token balance + total liquid tokens +
	// total remaining rewards + total unbonding balance
	NetAmount cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=net_amount,json=netAmount,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"net_amount"`
	// total_del_shares define the delegation shares of all liquid validators
	TotalDelShares cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=total_del_shares,json=totalDelShares,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_del_shares"`
	// total_liquid_tokens define the token amount worth of delegation shares of
	// all liquid validator (slashing applied amount)
	TotalLiquidTokens cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=total_liquid_tokens,json=totalLiquidTokens,proto3,customtype=cosmossdk.io/math.Int" json:"total_liquid_tokens"`
	// total_remaining_rewards define the sum of remaining rewards of proxy
	// account by all liquid validators
	TotalRemainingRewards cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=total_remaining_rewards,json=totalRemainingRewards,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_remaining_rewards"`
	// total_unbonding_balance define the unbonding balance of proxy account by
	// all liquid validator (slashing applied amount)
	TotalUnbondingBalance cosmossdk_io_math.Int `protobuf:"bytes,7,opt,name=total_unbonding_balance,json=totalUnbondingBalance,proto3,customtype=cosmossdk.io/math.Int" json:"total_unbonding_balance"`
	// proxy_acc_balance define the balance of proxy account for the native token
	ProxyAccBalance cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=proxy_acc_balance,json=proxyAccBalance,proto3,customtype=cosmossdk.io/math.Int" json:"proxy_acc_balance"`
}

func (m *NetAmountState) Reset()         { *m = NetAmountState{} }
func (m *NetAmountState) String() string { return proto.CompactTextString(m) }
func (*NetAmountState) ProtoMessage()    {}
func (*NetAmountState) Descriptor() ([]byte, []int) {
	return fileDescriptor_8f87e6d47a5a3bba, []int{4}
}
func (m *NetAmountState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetAmountState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NetAmountState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NetAmountState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetAmountState.Merge(m, src)
}
func (m *NetAmountState) XXX_Size() int {
	return m.Size()
}
func (m *NetAmountState) XXX_DiscardUnknown() {
	xxx_messageInfo_NetAmountState.DiscardUnknown(m)
}

var xxx_messageInfo_NetAmountState proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("pstake.liquidstake.v1beta1.ValidatorStatus", ValidatorStatus_name, ValidatorStatus_value)
	proto.RegisterType((*Params)(nil), "pstake.liquidstake.v1beta1.Params")
	proto.RegisterType((*WhitelistedValidator)(nil), "pstake.liquidstake.v1beta1.WhitelistedValidator")
	proto.RegisterType((*LiquidValidator)(nil), "pstake.liquidstake.v1beta1.LiquidValidator")
	proto.RegisterType((*LiquidValidatorState)(nil), "pstake.liquidstake.v1beta1.LiquidValidatorState")
	proto.RegisterType((*NetAmountState)(nil), "pstake.liquidstake.v1beta1.NetAmountState")
}

func init() {
	proto.RegisterFile("pstake/liquidstake/v1beta1/liquidstake.proto", fileDescriptor_8f87e6d47a5a3bba)
}

var fileDescriptor_8f87e6d47a5a3bba = []byte{
	// 1009 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x4d, 0x4f, 0x1b, 0xc7,
	0x1f, 0xc7, 0xbd, 0x04, 0xf8, 0xc3, 0x84, 0xf0, 0xb0, 0x98, 0xd8, 0x38, 0xff, 0x1a, 0x97, 0x5c,
	0x50, 0xda, 0xd8, 0x4d, 0xaa, 0xe6, 0xc0, 0xa1, 0xca, 0x1a, 0x13, 0xd5, 0x92, 0x01, 0x6b, 0x6d,
	0x43, 0xd5, 0x1e, 0xa6, 0xe3, 0x9d, 0xc1, 0x5e, 0x79, 0x77, 0x66, 0xbb, 0x33, 0x8b, 0xe1, 0x1d,
	0x44, 0x1c, 0xaa, 0x1e, 0x7b, 0x41, 0x8a, 0xd4, 0x43, 0xdf, 0x40, 0x5f, 0x44, 0x2e, 0x95, 0xa2,
	0x9e, 0xaa, 0x1e, 0x50, 0x05, 0x97, 0xf6, 0x5d, 0x54, 0x33, 0xb3, 0x6b, 0x1c, 0x93, 0x16, 0x13,
	0xf5, 0xb6, 0x9e, 0x99, 0xcf, 0x77, 0xbe, 0xfb, 0x7b, 0xf2, 0x82, 0x8f, 0x03, 0x2e, 0x50, 0x8f,
	0x94, 0x3c, 0xf7, 0xdb, 0xc8, 0xc5, 0xfa, 0xf9, 0xe8, 0x49, 0x9b, 0x08, 0xf4, 0x64, 0x78, 0xad,
	0x18, 0x84, 0x4c, 0x30, 0x33, 0xa7, 0x4f, 0x17, 0x87, 0x77, 0xe2, 0xd3, 0xb9, 0x74, 0x87, 0x75,
	0x98, 0x3a, 0x56, 0x92, 0x4f, 0x9a, 0xc8, 0xad, 0x3a, 0x8c, 0xfb, 0x8c, 0x43, 0xbd, 0xa1, 0x7f,
	0xe8, 0xad, 0xf5, 0xf3, 0x29, 0x30, 0x5d, 0x47, 0x21, 0xf2, 0xb9, 0xf9, 0x08, 0x2c, 0x69, 0x49,
	0xd8, 0x66, 0x14, 0x43, 0x4c, 0x28, 0xf3, 0xb3, 0x46, 0xc1, 0xd8, 0x98, 0xb5, 0x17, 0xf4, 0x46,
	0x99, 0x51, 0x5c, 0x91, 0xcb, 0xa6, 0x0f, 0xee, 0xf7, 0xbb, 0xae, 0x20, 0x9e, 0xcb, 0x05, 0xc1,
	0xf0, 0x08, 0x79, 0x2e, 0x46, 0x82, 0x85, 0x3c, 0x3b, 0x51, 0xb8, 0xb3, 0x71, 0xf7, 0xe9, 0x27,
	0xc5, 0x7f, 0x36, 0x59, 0x3c, 0xb8, 0x22, 0xf7, 0x13, 0xb0, 0x3c, 0xf9, 0xfa, 0x7c, 0x2d, 0x65,
	0xaf, 0xf4, 0xdf, 0xb1, 0xc7, 0xcd, 0x1d, 0xb0, 0x18, 0x51, 0x25, 0x02, 0x0f, 0x09, 0x81, 0x21,
	0x12, 0x24, 0x7b, 0x47, 0x3a, 0x2b, 0x3f, 0x94, 0xd8, 0xef, 0xe7, 0x6b, 0x0f, 0xf4, 0x5b, 0x71,
	0xdc, 0x2b, 0xba, 0xac, 0xe4, 0x23, 0xd1, 0x2d, 0xd6, 0x48, 0x07, 0x39, 0x27, 0x15, 0xe2, 0xd8,
	0xf3, 0x31, 0xfc, 0x82, 0x10, 0x1b, 0x09, 0x62, 0x7e, 0x08, 0xe6, 0x3c, 0xee, 0x43, 0xec, 0x72,
	0xd4, 0xf6, 0x08, 0xce, 0x4e, 0x16, 0x8c, 0x8d, 0x19, 0xfb, 0xae, 0xc7, 0xfd, 0x4a, 0xbc, 0x64,
	0x36, 0x41, 0xc6, 0x77, 0x29, 0x8c, 0x03, 0xa2, 0xaf, 0x46, 0x3e, 0x8b, 0xa8, 0xc8, 0x4e, 0xa9,
	0x8b, 0x3f, 0x88, 0x2f, 0x5e, 0xb9, 0x7e, 0x71, 0x95, 0x0a, 0x3b, 0xed, 0xbb, 0xb4, 0xa6, 0xe0,
	0x86, 0x64, 0x2d, 0x85, 0x9a, 0x3b, 0xe0, 0xbe, 0xd3, 0x87, 0x1e, 0x73, 0x7a, 0x04, 0xc3, 0x80,
	0x31, 0x0f, 0x22, 0x8c, 0x43, 0xc2, 0x79, 0x76, 0x5a, 0x89, 0x66, 0x7f, 0xfd, 0xf9, 0x71, 0x3a,
	0xce, 0x8f, 0xa5, 0x77, 0x1a, 0x22, 0x74, 0x69, 0xc7, 0x5e, 0x76, 0xfa, 0x35, 0x85, 0xd5, 0x19,
	0xf3, 0xe2, 0x2d, 0xf3, 0x0b, 0xb0, 0x2c, 0xc3, 0x81, 0x1c, 0x47, 0xaa, 0x0f, 0xb4, 0xfe, 0x77,
	0x83, 0xd6, 0xd2, 0x21, 0x21, 0x96, 0x66, 0x12, 0xa5, 0x03, 0xb0, 0x82, 0x22, 0xc1, 0x1c, 0xe6,
	0x07, 0x2c, 0xa2, 0xf8, 0x2a, 0xca, 0x33, 0xe3, 0x47, 0x79, 0x79, 0x58, 0x21, 0x09, 0x75, 0x1d,
	0x64, 0x06, 0x29, 0x85, 0x08, 0xcb, 0x98, 0x26, 0x36, 0x67, 0x6f, 0xb0, 0x79, 0x55, 0x0b, 0x96,
	0xe4, 0x12, 0xab, 0x0f, 0xc1, 0x3d, 0x9f, 0xe1, 0xc8, 0x23, 0x30, 0x40, 0x11, 0x27, 0x38, 0x0b,
	0x54, 0xf6, 0xe6, 0xf4, 0x62, 0x5d, 0xad, 0x6d, 0xce, 0xbc, 0x7c, 0xb5, 0x96, 0xfa, 0xe1, 0xd5,
	0x5a, 0x6a, 0xfd, 0x27, 0x03, 0xa4, 0xdf, 0x55, 0x70, 0xe6, 0x36, 0x58, 0x1a, 0x94, 0xed, 0xc0,
	0x93, 0x71, 0x83, 0xa7, 0xc5, 0x01, 0x92, 0xd8, 0x29, 0x83, 0x7b, 0x02, 0x85, 0x1d, 0x22, 0x60,
	0x9f, 0xb8, 0x9d, 0xae, 0xc8, 0x4e, 0x8c, 0x53, 0x1e, 0x73, 0x9a, 0x39, 0x50, 0xc8, 0xe6, 0xa4,
	0x74, 0xbb, 0xfe, 0x0d, 0x58, 0xd0, 0x15, 0x73, 0xe5, 0x71, 0x0b, 0x2c, 0xb2, 0x80, 0x84, 0xb7,
	0xb2, 0xb8, 0x90, 0x10, 0xf1, 0xb2, 0x8e, 0xc5, 0x9f, 0xf2, 0x86, 0xbf, 0x26, 0x40, 0x7a, 0xe4,
	0x8a, 0x86, 0x90, 0x59, 0xfa, 0x2f, 0xee, 0x31, 0x3f, 0x03, 0xd3, 0xb7, 0x09, 0x41, 0x7c, 0xd8,
	0xdc, 0x02, 0xd3, 0x5c, 0x20, 0x11, 0x71, 0xd5, 0xd1, 0xf3, 0x4f, 0x3f, 0xfa, 0xb7, 0xd1, 0xf1,
	0x96, 0xef, 0x88, 0xdb, 0x31, 0x6a, 0x96, 0x01, 0xc0, 0xc4, 0x83, 0xbc, 0x8b, 0x42, 0xc2, 0x55,
	0x3f, 0x8f, 0x59, 0xb4, 0xb3, 0x98, 0x78, 0x0d, 0x45, 0xc9, 0x4c, 0xc6, 0xed, 0x2e, 0x58, 0x8f,
	0x50, 0x3e, 0x5e, 0xa3, 0xcf, 0x69, 0xa6, 0xa9, 0x90, 0xa1, 0x58, 0x7f, 0x37, 0x05, 0xe6, 0x77,
	0x89, 0xd0, 0x8d, 0xaf, 0xa3, 0xfc, 0x1c, 0xcc, 0xfa, 0x2e, 0x15, 0xba, 0xb1, 0x8c, 0xf1, 0x3d,
	0xce, 0x48, 0x4a, 0x75, 0xd3, 0x1e, 0x48, 0x73, 0xd1, 0x3b, 0x0e, 0x42, 0x01, 0x05, 0x13, 0xc8,
	0x83, 0x3c, 0x0a, 0x02, 0xef, 0x64, 0xbc, 0x80, 0x9b, 0x31, 0xda, 0x94, 0x64, 0x43, 0x81, 0x32,
	0x6e, 0x94, 0x88, 0x64, 0xb2, 0xdd, 0x62, 0xa4, 0xce, 0xd2, 0xe4, 0xdd, 0xe4, 0x70, 0xd6, 0x66,
	0xde, 0x2f, 0x03, 0xf3, 0x0a, 0xae, 0x0c, 0xd2, 0xb0, 0x03, 0x96, 0xb5, 0xdc, 0x7b, 0x24, 0x63,
	0x49, 0x91, 0xb5, 0xa1, 0x8c, 0x98, 0x5f, 0x83, 0x8c, 0x96, 0x0b, 0x89, 0x8f, 0x5c, 0xea, 0xd2,
	0x0e, 0x0c, 0x49, 0x1f, 0x85, 0x38, 0x99, 0xb9, 0x63, 0x99, 0x5c, 0x51, 0x1a, 0x76, 0x22, 0x61,
	0x6b, 0x05, 0xb3, 0x95, 0x88, 0x47, 0x54, 0xfe, 0x67, 0x4a, 0xf1, 0x36, 0xf2, 0x10, 0x75, 0x48,
	0x3c, 0x84, 0x6f, 0xf0, 0xab, 0x65, 0x5b, 0x09, 0x5c, 0xd6, 0xac, 0x59, 0x05, 0x4b, 0x41, 0xc8,
	0x8e, 0x4f, 0xe4, 0x64, 0x1f, 0x08, 0xce, 0x8c, 0x23, 0xb8, 0xa0, 0x38, 0xcb, 0x71, 0x62, 0x29,
	0x55, 0x90, 0x86, 0x2c, 0xc8, 0x47, 0xbf, 0x18, 0x60, 0x61, 0xa4, 0x7d, 0xcc, 0xe7, 0xe0, 0xff,
	0xfb, 0x56, 0xad, 0x5a, 0xb1, 0x9a, 0x7b, 0x36, 0x6c, 0x34, 0xad, 0x66, 0xab, 0x01, 0x5b, 0xbb,
	0x8d, 0xfa, 0xf6, 0x56, 0xf5, 0x45, 0x75, 0xbb, 0xb2, 0x98, 0xca, 0xe5, 0x4f, 0xcf, 0x0a, 0xb9,
	0x11, 0xac, 0x45, 0x79, 0x40, 0x1c, 0xf7, 0xd0, 0x25, 0xd8, 0x7c, 0x06, 0x32, 0xd7, 0x14, 0xac,
	0xad, 0x66, 0x75, 0x7f, 0x7b, 0xd1, 0xc8, 0xad, 0x9e, 0x9e, 0x15, 0x56, 0x46, 0x60, 0xcb, 0x11,
	0xee, 0x11, 0x31, 0x37, 0xc1, 0xea, 0x35, 0xae, 0xba, 0x1b, 0x93, 0x13, 0xb9, 0x07, 0xa7, 0x67,
	0x85, 0xcc, 0x08, 0x59, 0xa5, 0x48, 0xb1, 0xb9, 0xc9, 0x97, 0x3f, 0xe6, 0x53, 0xe5, 0x2f, 0x5f,
	0x5f, 0xe4, 0x8d, 0x37, 0x17, 0x79, 0xe3, 0x8f, 0x8b, 0xbc, 0xf1, 0xfd, 0x65, 0x3e, 0xf5, 0xe6,
	0x32, 0x9f, 0xfa, 0xed, 0x32, 0x9f, 0xfa, 0xea, 0xf3, 0x8e, 0x2b, 0xba, 0x51, 0xbb, 0xe8, 0x30,
	0xbf, 0x14, 0x90, 0x90, 0xcb, 0xc1, 0x4f, 0x1d, 0xb2, 0x47, 0x49, 0x49, 0x8f, 0x96, 0xc7, 0x14,
	0x49, 0xa1, 0xd2, 0xd1, 0xb3, 0xd2, 0xf1, 0x5b, 0x1f, 0x5d, 0xe2, 0x24, 0x20, 0xbc, 0x3d, 0xad,
	0x3e, 0x8d, 0x3e, 0xfd, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x15, 0xea, 0x6c, 0xed, 0x97, 0x09, 0x00,
	0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ModulePaused {
		i--
		if m.ModulePaused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if len(m.WhitelistAdminAddress) > 0 {
		i -= len(m.WhitelistAdminAddress)
		copy(dAtA[i:], m.WhitelistAdminAddress)
		i = encodeVarintLiquidstake(dAtA, i, uint64(len(m.WhitelistAdminAddress)))
		i--
		dAtA[i] = 0x4a
	}
	{
		size := m.AutocompoundFeeRate.Size()
		i -= size
		if _, err := m.AutocompoundFeeRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if len(m.FeeAccountAddress) > 0 {
		i -= len(m.FeeAccountAddress)
		copy(dAtA[i:], m.FeeAccountAddress)
		i = encodeVarintLiquidstake(dAtA, i, uint64(len(m.FeeAccountAddress)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CwLockedPoolAddress) > 0 {
		i -= len(m.CwLockedPoolAddress)
		copy(dAtA[i:], m.CwLockedPoolAddress)
		i = encodeVarintLiquidstake(dAtA, i, uint64(len(m.CwLockedPoolAddress)))
		i--
		dAtA[i] = 0x32
	}
	{
		size := m.MinLiquidStakeAmount.Size()
		i -= size
		if _, err := m.MinLiquidStakeAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.LsmDisabled {
		i--
		if m.LsmDisabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.UnstakeFeeRate.Size()
		i -= size
		if _, err := m.UnstakeFeeRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.WhitelistedValidators) > 0 {
		for iNdEx := len(m.WhitelistedValidators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WhitelistedValidators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintLiquidstake(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.LiquidBondDenom) > 0 {
		i -= len(m.LiquidBondDenom)
		copy(dAtA[i:], m.LiquidBondDenom)
		i = encodeVarintLiquidstake(dAtA, i, uint64(len(m.LiquidBondDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WhitelistedValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WhitelistedValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WhitelistedValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TargetWeight.Size()
		i -= size
		if _, err := m.TargetWeight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintLiquidstake(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LiquidValidator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidValidator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidValidator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintLiquidstake(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LiquidValidatorState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidValidatorState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidValidatorState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.LiquidTokens.Size()
		i -= size
		if _, err := m.LiquidTokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.DelShares.Size()
		i -= size
		if _, err := m.DelShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.Status != 0 {
		i = encodeVarintLiquidstake(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.Weight.Size()
		i -= size
		if _, err := m.Weight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.OperatorAddress) > 0 {
		i -= len(m.OperatorAddress)
		copy(dAtA[i:], m.OperatorAddress)
		i = encodeVarintLiquidstake(dAtA, i, uint64(len(m.OperatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NetAmountState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetAmountState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NetAmountState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ProxyAccBalance.Size()
		i -= size
		if _, err := m.ProxyAccBalance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.TotalUnbondingBalance.Size()
		i -= size
		if _, err := m.TotalUnbondingBalance.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.TotalRemainingRewards.Size()
		i -= size
		if _, err := m.TotalRemainingRewards.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.TotalLiquidTokens.Size()
		i -= size
		if _, err := m.TotalLiquidTokens.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.TotalDelShares.Size()
		i -= size
		if _, err := m.TotalDelShares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.NetAmount.Size()
		i -= size
		if _, err := m.NetAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.StkxprtTotalSupply.Size()
		i -= size
		if _, err := m.StkxprtTotalSupply.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.MintRate.Size()
		i -= size
		if _, err := m.MintRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintLiquidstake(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintLiquidstake(dAtA []byte, offset int, v uint64) int {
	offset -= sovLiquidstake(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LiquidBondDenom)
	if l > 0 {
		n += 1 + l + sovLiquidstake(uint64(l))
	}
	if len(m.WhitelistedValidators) > 0 {
		for _, e := range m.WhitelistedValidators {
			l = e.Size()
			n += 1 + l + sovLiquidstake(uint64(l))
		}
	}
	l = m.UnstakeFeeRate.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	if m.LsmDisabled {
		n += 2
	}
	l = m.MinLiquidStakeAmount.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = len(m.CwLockedPoolAddress)
	if l > 0 {
		n += 1 + l + sovLiquidstake(uint64(l))
	}
	l = len(m.FeeAccountAddress)
	if l > 0 {
		n += 1 + l + sovLiquidstake(uint64(l))
	}
	l = m.AutocompoundFeeRate.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = len(m.WhitelistAdminAddress)
	if l > 0 {
		n += 1 + l + sovLiquidstake(uint64(l))
	}
	if m.ModulePaused {
		n += 2
	}
	return n
}

func (m *WhitelistedValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovLiquidstake(uint64(l))
	}
	l = m.TargetWeight.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	return n
}

func (m *LiquidValidator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovLiquidstake(uint64(l))
	}
	return n
}

func (m *LiquidValidatorState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAddress)
	if l > 0 {
		n += 1 + l + sovLiquidstake(uint64(l))
	}
	l = m.Weight.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	if m.Status != 0 {
		n += 1 + sovLiquidstake(uint64(m.Status))
	}
	l = m.DelShares.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.LiquidTokens.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	return n
}

func (m *NetAmountState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MintRate.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.StkxprtTotalSupply.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.NetAmount.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.TotalDelShares.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.TotalLiquidTokens.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.TotalRemainingRewards.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.TotalUnbondingBalance.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	l = m.ProxyAccBalance.Size()
	n += 1 + l + sovLiquidstake(uint64(l))
	return n
}

func sovLiquidstake(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozLiquidstake(x uint64) (n int) {
	return sovLiquidstake(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidBondDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidBondDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedValidators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedValidators = append(m.WhitelistedValidators, WhitelistedValidator{})
			if err := m.WhitelistedValidators[len(m.WhitelistedValidators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnstakeFeeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnstakeFeeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LsmDisabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.LsmDisabled = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinLiquidStakeAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinLiquidStakeAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CwLockedPoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CwLockedPoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeAccountAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeAccountAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AutocompoundFeeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AutocompoundFeeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistAdminAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistAdminAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModulePaused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ModulePaused = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WhitelistedValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WhitelistedValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WhitelistedValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetWeight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TargetWeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidValidator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidValidator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidValidator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidValidatorState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidValidatorState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidValidatorState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Weight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= ValidatorStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DelShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DelShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidTokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LiquidTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NetAmountState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetAmountState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetAmountState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MintRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StkxprtTotalSupply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StkxprtTotalSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NetAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalDelShares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalDelShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalLiquidTokens", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalLiquidTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRemainingRewards", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalRemainingRewards.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalUnbondingBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalUnbondingBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProxyAccBalance", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLiquidstake
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ProxyAccBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLiquidstake(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthLiquidstake
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLiquidstake(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLiquidstake
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLiquidstake
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthLiquidstake
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupLiquidstake
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthLiquidstake
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthLiquidstake        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLiquidstake          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupLiquidstake = fmt.Errorf("proto: unexpected end of group")
)
