chains:
  - name: gaia-4
    type: cosmos
    numValidators: 1
    ports:
      rpc: 26653
      rest: 1313
  - name: core-1
    type: persistencecore
    numValidators: 3
    upgrade:
      enabled: true
      type: build
      genesis: v7.0.0
      upgrades:
        - name: v8
          version: v8.0.0-rc3
    ports:
      rpc: 26657
      rest: 1317

relayers:
  - name: persistence-gaia
    type: hermes
    replicas: 1
    chains:
      - gaia-4
      - core-1

explorer:
  enabled: true
  ports:
    rest: 8080

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091
