chains:
  - name: test-gaia-1
    type: cosmos
    numValidators: 1
    ports:
      rpc: 26557
      rest: 1313
  - name: test-core-1
    type: persistencecore
    numValidators: 1
    upgrade:
      enabled: true
      type: build
      genesis: v7.0.3
      upgrades:
        - name: v8
          version: ajeet/sdk-v47
    resources:
      limits:
        cpu: "1"
        memory: "1Gi"
      requests:
        cpu: "1"
        memory: "1Gi"
    ports:
      rpc: 26657
      rest: 1317

relayers:
  - name: persistence-gaia
    type: go-relayer
    replicas: 1
    chains:
      - test-core-1
      - test-gaia-1
  - name: persistence-gaia
    type: icq
    replicas: 1
    chains:
      - test-core-1
      - test-gaia-1

registry:
  enabled: true
  ports:
    rest: 8081
    grpc: 9091
